### ISSUE TITLE
Example files?

### ISSUE THREAD

**Issue by PaulBatchelor** [fennecdjay/ff2spa#1]
Really excited to see soundpipe be used in interesting ways.

Is there any chance you could supply an example image or two to use?

**Comment by fennecdjay** [comment]
Nice to have some feedback on this project.
I'll try to provide something simple, as a square wave ASAP.

-----------
Anyway, if you install suckless's [Farbfled](http://tools.suckless.org/farbfeld/)
you can use `png2ff` to convert from png to farbfeld.
And you certainly already have [ImageMagick](http://git.imagemagick.org/repos/ImageMagick) installed, so you can probably feed `ff2spa` anything you like.
Yet it is only supposed to work with a single blask curve for now.
Anyway the source code is only 39 lines now, so there is much room for improvement.
I don't know for ` inkscape`, but the  [gimp plugin](https://github.com/ids1024/gimp-farbfeld)
should make it possible to have almost live feedback from the drawing with only little work.

**Comment by PaulBatchelor** [comment]
How is the image data converted to audio data, specifically? What is the relationship between the pixel and audio data.

If you haven't seen it already, I once did something similar [here](https://github.com/paulbatchelor/sporthdraw) using sporth raw output and imagemagick for the reverse process.

**Comment by fennecdjay** [comment]
:tada:
There is now a *gastric* (as in electro swing?) example my girlfriend made with gimp.
also two more little programs:

  * reader (`make reader-alsa` or `make reader-jack`)
    who loops argument file.
   * watcher (`make watcher`):
       who watches argument file and triggers a reader update when file is changed.


------------------------
Conversion from farbfeld to spa it pretty simple for now:
it reads from left to right, top to bottom, takes the lowest pixel non white pixel (I think) :smile: and everything is scaled between -1 and 1.

**Comment by PaulBatchelor** [comment]
right. I don't need the spa file. I can use your program to make that. The ff file would be better to have. Can you upload that?

**Comment by fennecdjay** [comment]
I migth have kept only the spa 😢 .
But I'll upload similar spa soon.

**Comment by PaulBatchelor** [comment]
I can also stop being lazy and try to make my own as well ;)

**Comment by fennecdjay** [comment]
There a new one: gastric2, both in png and farbfeld format. Maybe not quite as gastric as the former, but quite in the same mood.

Please note it is only a pretty lame drawing 😆

**Comment by PaulBatchelor** [comment]
thanks!

**Comment by fennecdjay** [comment]
Have fun!
let me know if you have any thougths about this projects, I'd really like it to grow.
